name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
env:
  GITHUB_USER: 'sandreas'
  PROJECT_NAME: 'Avalonia.Preferences'
  PROJECT_PATH: 'Avalonia.Preferences/Avalonia.Preferences.csproj'
  DOTNET_VERSION: '6.0.401'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.version.outputs.version-without-v }}
      
      #      - name: Test
      #        run: dotnet test --configuration Release /p:Version=${{ steps.version.outputs.version-without-v }} --no-build

      - name: Pack
        run: dotnet pack --configuration Release --include-symbols /p:Version=${{ steps.version.outputs.version-without-v }} --no-build --output .

      - name: Push
        run: |
          dotnet nuget push ${{ env.PROJECT_NAME }}.${{ steps.version.outputs.version-without-v }}.nupkg --source https://nuget.pkg.github.com/${{ env.GITHUB_USER }}/index.json --api-key ${GITHUB_TOKEN} && dotnet nuget push ${{ env.PROJECT_NAME }}.${{ steps.version.outputs.version-without-v }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}           
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
